/** Common dog and cat breeds for the add-pet breed picker. Optional field. */

export const DOG_BREEDS: string[] = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Bulldog",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Boston Terrier",
  "Boxer",
  "Brittany",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel",
  "Collie",
  "Corgi (Pembroke Welsh)",
  "Dachshund",
  "Dalmatian",
  "Doberman Pinscher",
  "English Setter",
  "English Springer Spaniel",
  "French Bulldog",
  "German Shepherd",
  "German Shorthaired Pointer",
  "Golden Retriever",
  "Great Dane",
  "Great Pyrenees",
  "Greyhound",
  "Havanese",
  "Irish Setter",
  "Jack Russell Terrier",
  "Labrador Retriever",
  "Maltese",
  "Mastiff",
  "Miniature Schnauzer",
  "Newfoundland",
  "Papillon",
  "Pekingese",
  "Pomeranian",
  "Poodle",
  "Portuguese Water Dog",
  "Pug",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saint Bernard",
  "Samoyed",
  "Schnauzer (Standard)",
  "Shar Pei",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Staffordshire Bull Terrier",
  "Vizsla",
  "Weimaraner",
  "West Highland White Terrier",
  "Whippet",
  "Yorkshire Terrier",
  "Mixed Breed",
];

export const CAT_BREEDS: string[] = [
  "Abyssinian",
  "American Shorthair",
  "Bengal",
  "Birman",
  "Bombay",
  "British Shorthair",
  "Burmese",
  "Chartreux",
  "Cornish Rex",
  "Devon Rex",
  "Domestic Longhair",
  "Domestic Shorthair",
  "Egyptian Mau",
  "Exotic Shorthair",
  "Himalayan",
  "Maine Coon",
  "Manx",
  "Norwegian Forest Cat",
  "Ocicat",
  "Oriental Shorthair",
  "Persian",
  "Ragdoll",
  "Russian Blue",
  "Savannah",
  "Scottish Fold",
  "Siamese",
  "Siberian",
  "Sphynx",
  "Tonkinese",
  "Turkish Angora",
  "Mixed Breed",
];

/** Breed suggestions for a given pet type ("other" has none). */
export function breedsForType(type: "dog" | "cat" | "other"): string[] {
  if (type === "dog") return DOG_BREEDS;
  if (type === "cat") return CAT_BREEDS;
  return [];
}
