/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedSafetyRouteImport } from './routes/_authenticated/safety'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPetCareGuidelinesRouteImport } from './routes/_authenticated/pet-care-guidelines'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedHowToUseRouteImport } from './routes/_authenticated/how-to-use'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHarassmentPreventionRouteImport } from './routes/_authenticated/harassment-prevention'
import { Route as AuthenticatedFaqRouteImport } from './routes/_authenticated/faq'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedCommunityGuidelinesRouteImport } from './routes/_authenticated/community-guidelines'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedReferralsIndexRouteImport } from './routes/_authenticated/referrals.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedRidesRideIdRouteImport } from './routes/_authenticated/rides.$rideId'
import { Route as AuthenticatedReferralsLeaderboardRouteImport } from './routes/_authenticated/referrals.leaderboard'
import { Route as AuthenticatedDriverVerifyRouteImport } from './routes/_authenticated/driver.verify'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafetyRoute = AuthenticatedSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetCareGuidelinesRoute =
  AuthenticatedPetCareGuidelinesRouteImport.update({
    id: '/pet-care-guidelines',
    path: '/pet-care-guidelines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHowToUseRoute = AuthenticatedHowToUseRouteImport.update({
  id: '/how-to-use',
  path: '/how-to-use',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHarassmentPreventionRoute =
  AuthenticatedHarassmentPreventionRouteImport.update({
    id: '/harassment-prevention',
    path: '/harassment-prevention',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaqRoute = AuthenticatedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityGuidelinesRoute =
  AuthenticatedCommunityGuidelinesRouteImport.update({
    id: '/community-guidelines',
    path: '/community-guidelines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsIndexRoute =
  AuthenticatedReferralsIndexRouteImport.update({
    id: '/referrals/',
    path: '/referrals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRidesRideIdRoute =
  AuthenticatedRidesRideIdRouteImport.update({
    id: '/rides/$rideId',
    path: '/rides/$rideId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferralsLeaderboardRoute =
  AuthenticatedReferralsLeaderboardRouteImport.update({
    id: '/referrals/leaderboard',
    path: '/referrals/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriverVerifyRoute =
  AuthenticatedDriverVerifyRouteImport.update({
    id: '/driver/verify',
    path: '/driver/verify',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/community-guidelines': typeof AuthenticatedCommunityGuidelinesRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/harassment-prevention': typeof AuthenticatedHarassmentPreventionRoute
  '/home': typeof AuthenticatedHomeRoute
  '/how-to-use': typeof AuthenticatedHowToUseRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pet-care-guidelines': typeof AuthenticatedPetCareGuidelinesRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/driver/verify': typeof AuthenticatedDriverVerifyRoute
  '/referrals/leaderboard': typeof AuthenticatedReferralsLeaderboardRoute
  '/rides/$rideId': typeof AuthenticatedRidesRideIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/referrals/': typeof AuthenticatedReferralsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/community-guidelines': typeof AuthenticatedCommunityGuidelinesRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/faq': typeof AuthenticatedFaqRoute
  '/harassment-prevention': typeof AuthenticatedHarassmentPreventionRoute
  '/home': typeof AuthenticatedHomeRoute
  '/how-to-use': typeof AuthenticatedHowToUseRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pet-care-guidelines': typeof AuthenticatedPetCareGuidelinesRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/driver/verify': typeof AuthenticatedDriverVerifyRoute
  '/referrals/leaderboard': typeof AuthenticatedReferralsLeaderboardRoute
  '/rides/$rideId': typeof AuthenticatedRidesRideIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/referrals': typeof AuthenticatedReferralsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/community-guidelines': typeof AuthenticatedCommunityGuidelinesRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/faq': typeof AuthenticatedFaqRoute
  '/_authenticated/harassment-prevention': typeof AuthenticatedHarassmentPreventionRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/how-to-use': typeof AuthenticatedHowToUseRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pet-care-guidelines': typeof AuthenticatedPetCareGuidelinesRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/safety': typeof AuthenticatedSafetyRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/_authenticated/driver/verify': typeof AuthenticatedDriverVerifyRoute
  '/_authenticated/referrals/leaderboard': typeof AuthenticatedReferralsLeaderboardRoute
  '/_authenticated/rides/$rideId': typeof AuthenticatedRidesRideIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/referrals/': typeof AuthenticatedReferralsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community-guidelines'
    | '/earnings'
    | '/emergency'
    | '/faq'
    | '/harassment-prevention'
    | '/home'
    | '/how-to-use'
    | '/messages'
    | '/notifications'
    | '/pet-care-guidelines'
    | '/pricing'
    | '/profile'
    | '/safety'
    | '/trips'
    | '/driver/verify'
    | '/referrals/leaderboard'
    | '/rides/$rideId'
    | '/api/public/stripe-webhook'
    | '/referrals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/community-guidelines'
    | '/earnings'
    | '/emergency'
    | '/faq'
    | '/harassment-prevention'
    | '/home'
    | '/how-to-use'
    | '/messages'
    | '/notifications'
    | '/pet-care-guidelines'
    | '/pricing'
    | '/profile'
    | '/safety'
    | '/trips'
    | '/driver/verify'
    | '/referrals/leaderboard'
    | '/rides/$rideId'
    | '/api/public/stripe-webhook'
    | '/referrals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/community-guidelines'
    | '/_authenticated/earnings'
    | '/_authenticated/emergency'
    | '/_authenticated/faq'
    | '/_authenticated/harassment-prevention'
    | '/_authenticated/home'
    | '/_authenticated/how-to-use'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/pet-care-guidelines'
    | '/_authenticated/pricing'
    | '/_authenticated/profile'
    | '/_authenticated/safety'
    | '/_authenticated/trips'
    | '/_authenticated/driver/verify'
    | '/_authenticated/referrals/leaderboard'
    | '/_authenticated/rides/$rideId'
    | '/api/public/stripe-webhook'
    | '/_authenticated/referrals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety': {
      id: '/_authenticated/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AuthenticatedSafetyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pet-care-guidelines': {
      id: '/_authenticated/pet-care-guidelines'
      path: '/pet-care-guidelines'
      fullPath: '/pet-care-guidelines'
      preLoaderRoute: typeof AuthenticatedPetCareGuidelinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/how-to-use': {
      id: '/_authenticated/how-to-use'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof AuthenticatedHowToUseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/harassment-prevention': {
      id: '/_authenticated/harassment-prevention'
      path: '/harassment-prevention'
      fullPath: '/harassment-prevention'
      preLoaderRoute: typeof AuthenticatedHarassmentPreventionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faq': {
      id: '/_authenticated/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AuthenticatedFaqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community-guidelines': {
      id: '/_authenticated/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof AuthenticatedCommunityGuidelinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals/': {
      id: '/_authenticated/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof AuthenticatedReferralsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rides/$rideId': {
      id: '/_authenticated/rides/$rideId'
      path: '/rides/$rideId'
      fullPath: '/rides/$rideId'
      preLoaderRoute: typeof AuthenticatedRidesRideIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals/leaderboard': {
      id: '/_authenticated/referrals/leaderboard'
      path: '/referrals/leaderboard'
      fullPath: '/referrals/leaderboard'
      preLoaderRoute: typeof AuthenticatedReferralsLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver/verify': {
      id: '/_authenticated/driver/verify'
      path: '/driver/verify'
      fullPath: '/driver/verify'
      preLoaderRoute: typeof AuthenticatedDriverVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCommunityGuidelinesRoute: typeof AuthenticatedCommunityGuidelinesRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedFaqRoute: typeof AuthenticatedFaqRoute
  AuthenticatedHarassmentPreventionRoute: typeof AuthenticatedHarassmentPreventionRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedHowToUseRoute: typeof AuthenticatedHowToUseRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPetCareGuidelinesRoute: typeof AuthenticatedPetCareGuidelinesRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSafetyRoute: typeof AuthenticatedSafetyRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
  AuthenticatedDriverVerifyRoute: typeof AuthenticatedDriverVerifyRoute
  AuthenticatedReferralsLeaderboardRoute: typeof AuthenticatedReferralsLeaderboardRoute
  AuthenticatedRidesRideIdRoute: typeof AuthenticatedRidesRideIdRoute
  AuthenticatedReferralsIndexRoute: typeof AuthenticatedReferralsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCommunityGuidelinesRoute: AuthenticatedCommunityGuidelinesRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedFaqRoute: AuthenticatedFaqRoute,
  AuthenticatedHarassmentPreventionRoute:
    AuthenticatedHarassmentPreventionRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedHowToUseRoute: AuthenticatedHowToUseRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPetCareGuidelinesRoute: AuthenticatedPetCareGuidelinesRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSafetyRoute: AuthenticatedSafetyRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
  AuthenticatedDriverVerifyRoute: AuthenticatedDriverVerifyRoute,
  AuthenticatedReferralsLeaderboardRoute:
    AuthenticatedReferralsLeaderboardRoute,
  AuthenticatedRidesRideIdRoute: AuthenticatedRidesRideIdRoute,
  AuthenticatedReferralsIndexRoute: AuthenticatedReferralsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
